eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 160000000
