eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms